name: Build projects and run tests

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build Projects
      run: |
        dotnet build ./src/LinqKit/LinqKit.csproj -c Release
        dotnet build ./src/LinqKit.EntityFramework/LinqKit.EntityFramework.csproj -c Release
        dotnet build ./src/LinqKit.Microsoft.EntityFrameworkCore/LinqKit.Microsoft.EntityFrameworkCore.csproj -c Release
        dotnet build ./src/LinqKit.Z.EntityFramework.Classic/LinqKit.Z.EntityFramework.Classic.csproj -c Release
    
    - name: Run Tests
      run: |
        dotnet test --no-build ./tests/LinqKit.Tests/LinqKit.Tests.csproj -c Release
        dotnet test --no-build ./tests/LinqKit.EntityFramework.Tests.Net452/LinqKit.EntityFramework.Tests.Net452.csproj -c Release
        dotnet test --no-build ./tests/LinqKit.Microsoft.EntityFrameworkCore.Tests -c Release
        
    - name: Package Projects
      run: |
        dotnet publish ./src/LinqKit/LinqKit.csproj -c Release
        dotnet publish ./src/LinqKit.EntityFramework/LinqKit.EntityFramework.csproj -c Release
        dotnet publish ./src/LinqKit.Microsoft.EntityFrameworkCore/LinqKit.Microsoft.EntityFrameworkCore.csproj -c Release
        dotnet publish ./src/LinqKit.Z.EntityFramework.Classic/LinqKit.Z.EntityFramework.Classic.csproj -c Release
        
    - name: Publish to Github
      run: echo "hello"
